### ISSUE TITLE
I need help to use android google maps private api

### ISSUE THREAD

**Issue by emma-eva** [socialAPIS/YoutubeDownloader#1]
I am using your youtube private api codes and i am very happy to use it. Now i am interest to use android google maps private api with signin/login features (gmail login), so i need your help. Mail me plz: keya5racc@gmail.com

Advance Thanks ;)

**Comment by socialAPIS** [comment]
Thank you, i will contact you soon.

**Comment by emma-eva** [comment]
Still waiting :)
