### ISSUE TITLE
I need a special api for youtube.

### ISSUE THREAD

**Issue by SuhatAkbulak** [socialAPIS/YoutubeDownloader#2]
hello sir.Please contact me.My mail suhatakbulak@gmail.com

**Comment by socialAPIS** [comment]
You can write here your needs, what the api should do and then we can see what we can do

**Comment by SuhatAkbulak** [comment]
I just want an encryption for likes and subscribers requests.I need code written in a simple way.
I am ready to pay you for this.

**Comment by socialAPIS** [comment]
I contacted you on email
