### ISSUE TITLE
Error Run in localhost Warning: count(): Parameter must be an array or an object that implements 

### ISSUE THREAD

**Issue by boshenry** [socialAPIS/YoutubeDownloader#4]
Hello, 

I try to run example on localhost. 
It seems good but i've got this error

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\youtube\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67

And how to get 1080p video?

Thanks

**Comment by socialAPIS** [comment]
Which link did you used?
